/**
 * Фикстуры выводов tsh 17.0.4 (сервер 17.0.1): форма и порядок полей — как отдаёт
 * tsh, содержимое выдумано. При обновлении tsh/кластера — перепроверить (NFR-7).
 */

export const PASSWORD_PROMPT = 'Enter password for Teleport user user@example.com:'
export const OTP_PROMPT = 'Enter an OTP code from a device:'

export const STATUS_JSON_LOGGED_IN = `{
  "active": {
    "profile_url": "https://teleport.example.com:443",
    "username": "user@example.com",
    "cluster": "teleport.example.com",
    "roles": ["access", "db-access", "kube-access"],
    "kubernetes_enabled": true,
    "kubernetes_cluster": "stage-k8s-cluster",
    "kubernetes_groups": ["developers"],
    "databases": ["dev-postgres", "prod-postgres"],
    "valid_until": "2026-07-29T04:27:47+04:00",
    "extensions": ["login-ip", "permit-port-forwarding", "permit-pty", "private-key-policy"]
  },
  "profiles": []
}`

export const STATUS_NOT_LOGGED_IN_STDERR = 'ERROR: Not logged in.'

/**
 * Вывод `tsh mfa add --type TOTP` — ВНИМАНИЕ: реконструкция по исходникам tsh
 * 17.x, на живом кластере пока не снята. При первом прогоне мастера сверить
 * дословно и обновить (NFR-7). Секрет здесь — тестовый, не настоящий.
 */
export const MFA_ADD_EXISTING_PROMPT = 'Enter an OTP code from a *registered* device:'
export const MFA_ADD_SECRET_BLOCK = `Open your TOTP app and create a new manual entry with these fields:
  URL: otpauth://totp/teleport.example.com:user%40example.com?algorithm=SHA1&digits=6&issuer=teleport.example.com&period=30&secret=JBSWY3DPEHPK3PXPJBSWY3DP
  Account name: user@example.com
  Issuer: teleport.example.com
  Algorithm: SHA1
  Period: 30s
  Digits: 6
`
export const MFA_ADD_NEW_PROMPT = 'Once created, enter an OTP code generated by the new device:'
export const MFA_ADD_TEST_SECRET = 'JBSWY3DPEHPK3PXPJBSWY3DP'
