import type { PromptPatterns } from '../../services/PromptPipeline'

/**
 * Дословные промпты tsh 17.x (проверено на живом кластере, docs/04 §3.1).
 * Версия-специфика Teleport изолирована здесь + покрыта фикстурными тестами (NFR-7).
 */
export const TELEPORT_PROMPT_PATTERNS: PromptPatterns = {
  password: /Enter password for Teleport user .+:$/,
  otp: /Enter an OTP code from a device:$/
}

/**
 * Промпты мастера `tsh mfa add --type TOTP` (docs/04 §4.2).
 * ВНИМАНИЕ: сняты с исходников tsh 17.x, на живом кластере пока не проверены —
 * при первом прогоне мастера сверить и поправить фикстуры (NFR-7).
 */
export const MFA_ADD_PATTERNS = {
  /** Код СУЩЕСТВУЮЩЕГО девайса (G2FA) — вводит пользователь руками. */
  existing: /OTP code from a \*?registered\*? device:$/i,
  /** Код НОВОГО девайса — генерируем сами из перехваченного секрета. */
  newDevice: /OTP code generated by the new device:$/i
}

/**
 * «Нужен перелогин» в stderr exec-канала (docs/04 §6, п.2). Набор дополняем по
 * мере встречи новых формулировок — фикстуры в __fixtures__/kube.ts (NFR-7).
 */
export const AUTH_ERROR_PATTERNS = [
  // «ssh: cert has expired», «your Teleport session has expired» — снято вживую
  /expired/i,
  /re-?login/i,
  /access denied/i,
  /not logged in/i
]

export const isAuthError = (stderr: string): boolean =>
  AUTH_ERROR_PATTERNS.some((re) => re.test(stderr))

/**
 * Per-session MFA у exec-канала: интерактивный промпт в неинтерактивном запуске.
 * Такой запрос повторяем через PTY-обёртку (docs/04 §3.3).
 */
export const MFA_REQUIRED_PATTERNS = [
  /MFA (is )?required/i,
  /per-session MFA/i,
  /multi-?factor/i,
  /Enter an OTP code/i
]

export const isMfaError = (stderr: string): boolean =>
  MFA_REQUIRED_PATTERNS.some((re) => re.test(stderr))

/** Секрет нового девайса из вывода tsh: otpauth-URL либо строка «Secret …». */
export const TOTP_SECRET_PATTERNS = [
  /otpauth:\/\/totp\/\S*[?&]secret=([A-Z2-7]{16,})/i,
  /Secret(?:\s+key)?:\s*([A-Z2-7]{16,})(?:\s|$)/i
]
